/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: rg.i

package rg

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_rg_dcf42f4469ec1621(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_rg_dcf42f4469ec1621(swig_intgo arg1);
extern void _wrap_random_matrix_rg_dcf42f4469ec1621(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
#undef intgo
*/
// #cgo CPPFLAGS: -fopenmp
// #cgo CXXFLAGS: -fopenmp
// #cgo CFLAGS: -fopenmp
// #cgo LDFLAGS: -O2 -fopenmp -L/home/aleksandr_vasilchenko/go/src/github.com/krux02/swig-test/rg -lRg
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_rg_dcf42f4469ec1621(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_rg_dcf42f4469ec1621(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Random_matrix(arg1 int, arg2 int, arg3 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_random_matrix_rg_dcf42f4469ec1621(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2))
}
